### ISSUE TITLE
PamMap.hpp vs. pammap.hpp

### ISSUE THREAD

**Issue by maxscheurer** [mfherbst/pammap#11]
After cloning the repository, executing `git status`, I get:

```
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   pammap/core/PamMap.hpp

no changes added to commit (use "git add" and/or "git commit -a")
```

Subsequently, the build fails of course, since `PamMap.hpp` is included in most files.
I could fix this executing `git checkout pammap/core/PamMap.hpp`. 
However, `pammap/core/tests/test.cpp` still includes `pammap.hpp` in line 20, such that building
tests fails.

**Comment by maxscheurer** [comment]
Nope... The behavior I described happens after a clean/fresh `git clone` of the repository, so I did not change any files. There is no `pammap/core/PamMap.hpp` file, but `pammap/core/pammap.hpp` only...
This is odd because in the GitHub file browser, the file is named correctly.

Contents of my `pammap.hpp` file are:

```
//
// Copyright (C) 2018 by Michael F. Herbst and contributors
//
// This file is part of pammap.
//
// pammap is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// pammap is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with pammap. If not, see <http://www.gnu.org/licenses/>.
//

#pragma once
#include "ArrayView.hpp"
#include "PamMap.hpp"
#include "Slice.hpp"
#include "any.hpp"
#include "typedefs.hxx"
```

**Comment by mfherbst** [comment]
I mean on windows or with case-insensitive file names those files are certainly the same ... but on MacOS this should not be an issue. Nevertheless I will rename one of the files for clarity.

**Comment by mfherbst** [comment]
The file you show is in fact the content of `pammap.hpp` and not the content of `PamMap.hpp`. Still ... a really odd behaviour.

**Comment by maxscheurer** [comment]
Apple introduced a new file system (APFS), which is has case-insensitive file names (😠). That
explains it...

**Comment by mfherbst** [comment]
I do intend to support MacOS products, so reopening the issue. But honestly ... why would you do this? Is there any good reason for a case-insensitive file system?

**Comment by maxscheurer** [comment]
I did not create and/or design the file system 😂 
Please refer to the [APFS guide](https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/APFS_Guide/FAQ/FAQ.html).
I did not know about that until a minute ago, so annoying...

**Comment by mfherbst** [comment]
Ah so it is just case insensitive by default, but can be configured to be case-sensitve. Not sure why you would do it this way round. Thanks for the link. I'll keep that in mind for the future.

**Comment by mfherbst** [comment]
PR #20 will rename the `pammap.hpp` file, which should fix this issue.
